# ~/.bashrc for Jupyter container

# Enable programmable completion features
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# Set some shell options
shopt -s checkwinsize  # Update window size after each command
shopt -s histappend    # Append to history instead of overwriting
shopt -s cmdhist       # Save multi-line commands in history

# Set history format
HISTCONTROL=ignoreboth
HISTSIZE=1000
HISTFILESIZE=2000

# Set a more informative prompt
PS1='\[\033[01;32m\]\u@jupyter\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

# Some useful aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ..='cd ..'
alias ...='cd ../..'
alias kg="kaggle"

# Add user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi