version: '3.8'

services:
  ml-app:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
      - ./models:/app/models
      - ./notebooks:/app/notebooks
    environment:
      - PYTHONPATH=/app
    ports:
      - "8888:8888"  # Jupyter Lab port
    command: poetry run jupyter lab --ip 0.0.0.0 --port 8888 --no-browser --allow-root